DROP TABLE IF EXISTS favorite CASCADE;
CREATE TABLE favorite (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  favorite_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
